services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./db/mysql/.env
    volumes:
#      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - ./db/mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - els-network

  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    command: redis-server --appendonly yes
    networks:
      - els-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - els-network

  zipkin:
    image: openzipkin/zipkin:latest-arm64
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    ports:
      - "9411:9411"
    depends_on:
      - elasticsearch
    networks:
      - els-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.23
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - els-network

networks:
  els-network:
    driver: bridge
