spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testDb
    #url: jdbc:h2:file:/Users/parkkyutae/Documents/sources/github/fastcampus-demo-01/record-example/sample1/backofficeDb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

    properties:
      hibernate:
        format_sql: true
        show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html

  mail:
    username: test.email.12588
    password: jqvozceuwvacbxwa
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace

  file:
    name: ./logs/spring-jpa.log

######### 네이버 API
naver-api:
  client-id: goQZ03tXlaISGqa0Lgau
  client-secret: WPVuMeYLHS