spring:
  application:
    name: delivery-api

  boot:
    admin:
      client:
        url:
          - http://localhost:8085

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    expired-hour: 1
  refresh-token:
    expired-hour: 12

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback.xml
  file:
    name: api/logs/logFile.log