apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Chart.Name }}