server:
  port: 8005

grpc:
  server:
    port: 9091

spring:
  application:
    name: els-enrollment

  datasource:
    url: jdbc:mysql://localhost:3306/enrollment?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bobby
    password: 1234

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  sql:
    init:
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema-mysql.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi

  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus