server:
  port: 9010

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

---

spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 63790
