spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: book-api
          uri: lb://book-api
          order: 1
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books/(?<segment>.*), /v1/books/$\{segment}

        - id: payment-api
          uri: lb://payment-api
          order: 1
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/payments/(?<segment>.*), /v1/payments/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: 1ad35d74dc65cc0ee9a3a409f7f87e332aa6aa89d9cc64c66cdf9a1ffdc534ee