spring:
  config:
    activate:
      on-profile: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      bean-classes: org.example.trxbatch.service.email.MonthlyTrxReportBulkEmailService
    assaults:
      level: 3
      exceptions-active: true
      deterministic: true
      exception:
        type: org.example.trxbatch.exception.TrxBatchEmailServerCommunicationException

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"