spring:
  config:
    activate:
      on-profile: chaos-monkey

#chaos:
#  monkey:
#    enabled: true
#    watcher:
#      bean-classes: org.example.trxbatch.service.email.MonthlyTrxReportBulkEmailService
#    assaults:
#      level: 3
#      exceptions-active: true
#      deterministic: true
#      exception:
#        type: org.example.trxbatch.exception.TrxBatchEmailServerCommunicationException

chaos:
  monkey:
    enabled: true
    watcher:
      repository: true
    assaults:
      level: 1
      kill-application-active: true
      latency-active: true
      latency-range-start: 100
      latency-range-end: 1000

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"