oauth:
  google:
    oauth-url: https://accounts.google.com/o/oauth2/v2/auth
    access-token-url: https://oauth2.googleapis.com/token
    user-info-url: https://www.googleapis.com/oauth2/v1/userinfo
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/google/approve
    scope: profile email

  naver:
    oauth-url: https://nid.naver.com/oauth2.0/authorize
    access-token-url: https://nid.naver.com/oauth2.0/token
    user-info-url: https://openapi.naver.com/v1/nid/me
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/naver/approve

  kakao:
    oauth-url: https://kauth.kakao.com/oauth/authorize
    access-token-url: https://kauth.kakao.com/oauth/token
    user-info-url: https://kapi.kakao.com/v2/user/me
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/kakao/approve