oauth:
  google:
    oauth-url: https://accounts.google.com/o/oauth2/v2/auth
    access-token-url: https://oauth2.googleapis.com/token
    user-info-url: https://www.googleapis.com/oauth2/v1/userinfo
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/google/approve
    scope: profile email