## H2
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: user
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

spring:
  cloud:
    vault:
      token: hvs.CAESIKSFIQl8AEXULEo8JbKkbN0IjzdriYmKvHwKNUUBxkEuGh4KHGh2cy45Q0dySGpWdVpvYm9ja2VQWFdWcUNMWkU
      scheme: http
      host: localhost
      port: 8200