grpc:
  server:
    port: 9093

server:
  port: 8006

spring:
  application:
    name: els-chat

  data:
    redis:
      host: localhost
      port: 16379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    registerWithEureka: true
    fetchRegistry: true
