logging:
  level:
    root: info

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sns
    username: root
    password: 1234

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234