server:
  port: 8888

spring:
  application:
    name: config-server

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file:///${user.home}/Desktop/study/native
          search-locations: file://${user.home}/Desktop/kim/study/native
        git:
#          uri: file://C:/Users/Woojin/Desktop/study/config
          uri: file:///Users/bobby/Desktop/kim/study/config
#          uri: [github_uri]
#          username: [your username]
#          password: [your password]
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
