spring:
  application:
    name: paymentservice

  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:10000, localhost:10001, localhost:10002
          required-acks: all
          auto-create-topics: false

        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

      bindings:
        send-out-0:
          destination: payment
          group: payment-service

psp:
  toss:
    url: https://api.tosspayments.com
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

management:
  endpoints:
    web:
      exposure:
        include: bindings