spring:
  application:
    name: els-graphql

  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: true
    schema:
      inspection:
        enabled: true

  data:
    redis:
      host: localhost
      port: 16379
      client-type: lettuce

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    registerWithEureka: true
    fetchRegistry: true

grpc:
  client:
    els-playback:
      address: 'discovery:///els-playback'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    els-payment:
      address: 'discovery:///els-enrollment'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    els-enrollment:
      address: 'discovery:///els-enrollment'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext