spring:
  application:
    name: grpc-client
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9090'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
