spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1234

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
      add-mappings: true