version: '3.1'

services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'inventory'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'

  redis:
    image: redis:7.2
    command: redis-server --requirepass 1234
    ports:
      - '6379:6379'