spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: study
    password: study

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true
