spring:
  profiles:
    active: chaos-monkey

  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: study
    password: study

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey

chaos:
  monkey:
    watcher:
      repository: true