spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: batch
    password: 1234
  batch:
    initialize-schema: always
    job:
      names: ${job.name:createArticleJob}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
