spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: best
  profiles:
    active: default

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

server:
  port: 8084

logging:
  level:
    org.hibernate.SQL: debug